<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    
    <TargetFramework>net472</TargetFramework>
    <AssemblyName>CustomTranslator</AssemblyName>
    <RootNamespace>CustomTranslator</RootNamespace>
   
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <!--指定具体的 BlishHUD 支持版本 -->
    <PackageReference Include="BlishHUD" Version="1.3.0" />
    <PackageReference Include="MonoMod.RuntimeDetour" Version="22.3.23.2" />
    <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.1.303" />
  </ItemGroup>

</Project>
