<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0-windows</TargetFramework>
    <AssemblyName>CustomTranslator</AssemblyName>
    <RootNamespace>CustomTranslator</RootNamespace>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlishHUD" Version="0.11.8" />
  </ItemGroup>

</Project>
