name: 云端自动编译打包
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 设置 .NET 编译环境
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0.x'

      - name: 开始编译
        run: dotnet build --configuration Release

      - name: 打包为 BHM 插件
        run: |
          mkdir out
          copy manifest.json out\
          copy bin\Release\net6.0\CustomTranslator.dll out\
          powershell Compress-Archive -Path out\* -DestinationPath CustomTranslator.bhm

      - name: 上传成品
        uses: actions/upload-artifact@v4
        with:
          name: 编译好的汉化插件
          path: CustomTranslator.bhm
